#!/usr/bin/env python3
"""
Generate Inno Setup script for dual installer (CLI + GUI).
Output: pixiv_login_installer_dual.iss
"""
from __future__ import annotations
import json
import uuid
from pathlib import Path

PRODUCT_NAME = "Pixiv OAuth"
PUBLISHER = "Fatony Ahmad Fauzi"
EXE_CLI = r"dist_portable\pixiv_login_plus.exe"
EXE_GUI = r"dist_gui\pixiv_login_gui.exe"
OUT_DIR = "dist_installer"

# Keep a stable AppId GUID across regenerations by storing it (optional).
GUID_FILE = Path("installer_guid.txt")

def load_version() -> str:
    p = Path("version.json")
    if not p.exists():
        return "1.0.0"
    try:
        return json.loads(p.read_text(encoding="utf-8")).get("version", "1.0.0")
    except Exception:
        return "1.0.0"

def load_or_create_guid() -> str:
    if GUID_FILE.exists():
        g = GUID_FILE.read_text(encoding="utf-8").strip()
        if g:
            return g
    g = str(uuid.uuid4()).upper()
    GUID_FILE.write_text(g, encoding="utf-8")
    return g

def main():
    ver = load_version()
    appid = load_or_create_guid()

    iss = f"""\
; Auto-generated by make_installer_iss_dual.py
; Do not edit manually unless you know what you're doing.

#define ProductName "{PRODUCT_NAME}"
#define ProductVersion "{ver}"
#define Publisher "{PUBLISHER}"
#define ExeCLI "{EXE_CLI}"
#define ExeGUI "{EXE_GUI}"

[Setup]
AppId={{{{{appid}}}}}
AppName={{#ProductName}}
AppVersion={{#ProductVersion}}
AppPublisher={{#Publisher}}
DefaultDirName={{autopf}}\\{{#ProductName}}
DefaultGroupName={{#ProductName}}
DisableProgramGroupPage=yes
OutputDir={OUT_DIR}
OutputBaseFilename=PixivLoginSetup_v{{#ProductVersion}}
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
ArchitecturesInstallIn64BitMode=x64compatible
UninstallDisplayIcon={{app}}\\pixiv_login_gui.exe

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

; --- Types let user pick CLI/GUI easily ---
[Types]
Name: "full"; Description: "Install CLI + GUI"
Name: "cli"; Description: "Install CLI only"
Name: "gui"; Description: "Install GUI only"
Name: "custom"; Description: "Custom installation"; Flags: iscustom

[Components]
Name: "cli"; Description: "Pixiv OAuth CLi"; Types: full cli custom; Flags: fixed
Name: "gui"; Description: "Pixiv OAuth GUi"; Types: full gui custom

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop icon for GUi"; GroupDescription: "Additional icons:"; Components: gui
Name: "addtopath"; Description: "Add CLi to PATH (recommended)"; GroupDescription: "CLI options:"; Components: cli

[Files]
Source: "{{#ExeCLI}}"; DestDir: "{{app}}"; Flags: ignoreversion; Components: cli
Source: "{{#ExeGUI}}"; DestDir: "{{app}}"; Flags: ignoreversion; Components: gui

[Icons]
Name: "{{group}}\\Pixiv OAuth GUi"; Filename: "{{app}}\\pixiv_login_gui.exe"; Components: gui
Name: "{{group}}\\Pixiv OAuth CLi"; Filename: "{{app}}\\pixiv_login_plus.exe"; Components: cli
Name: "{{commondesktop}}\\Pixiv OAuth GUi"; Filename: "{{app}}\\pixiv_login_gui.exe"; Tasks: desktopicon; Components: gui

[Run]
Filename: "{{app}}\\pixiv_login_gui.exe"; Description: "Launch Pixiv OAuth GUi"; Flags: nowait postinstall skipifsilent; Components: gui
Filename: "{{app}}\\pixiv_login_plus.exe"; Description: "Launch Pixiv OAuth CLi"; Flags: nowait postinstall skipifsilent; Components: cli

[Code]
function NeedsAddPath(Param: string): Boolean;
begin
  Result := (Param = 'addtopath');
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  PathEnv, NewPath: string;
begin
  if (CurStep = ssPostInstall) and WizardIsTaskSelected('addtopath') then begin
    if not RegQueryStringValue(HKCU, 'Environment', 'Path', PathEnv) then
      PathEnv := '';

    if Pos(ExpandConstant('{{app}}'), PathEnv) = 0 then begin
      if (PathEnv <> '') and (Copy(PathEnv, Length(PathEnv), 1) <> ';') then
        PathEnv := PathEnv + ';';
      NewPath := PathEnv + ExpandConstant('{{app}}');
      RegWriteStringValue(HKCU, 'Environment', 'Path', NewPath);
      // Tell Explorer to reload env vars
      SendMessageTimeout(HWND_BROADCAST, WM_SETTINGCHANGE, 0, 'Environment', SMTO_ABORTIFHUNG, 5000, NewPath);
    end;
  end;
end;
"""

    Path("pixiv_login_installer_dual.iss").write_text(iss, encoding="utf-8")
    print("Wrote pixiv_login_installer_dual.iss (version:", ver, "AppId:", appid + ")")

if __name__ == "__main__":
    main()
