#!/usr/bin/env python3
"""
Generate Inno Setup script for dual installer (CLI + GUI).
Output: pixiv_login_installer_dual.iss
"""
from __future__ import annotations
import json
import uuid
from pathlib import Path

PRODUCT_NAME = "Pixiv OAuth"
PUBLISHER = "Fatony Ahmad Fauzi"
EXE_CLI = r"build\portable\pixiv_login_plus.exe"
EXE_GUI = r"build\gui\pixiv_login_gui.exe"
OUT_DIR = r"build\installer"
ICON_FILE = r"app\pixiv_oauth.ico"

# Keep a stable AppId GUID across regenerations by storing it (optional).
GUID_FILE = Path(__file__).parent / "installer_guid.txt"

def load_identity() -> tuple[str, str]:
    # version.json is at project root, so checking CWD or parent is useful
    p = Path(__file__).parent.parent / "version.json"
    if not p.exists():
        p = Path("version.json")
    if not p.exists():
        return "1.0.0", "BUILD-UNKNOWN"
    try:
        raw = json.loads(p.read_text(encoding="utf-8"))
        return str(raw.get("version", "1.0.0")), str(raw.get("build_code", "BUILD-UNKNOWN"))
    except Exception:
        return "1.0.0", "BUILD-UNKNOWN"

def load_or_create_guid() -> str:
    if GUID_FILE.exists():
        g = GUID_FILE.read_text(encoding="utf-8").strip()
        if g:
            return g
    g = str(uuid.uuid4()).upper()
    GUID_FILE.write_text(g, encoding="utf-8")
    return g

def main():
    ver, build_code = load_identity()
    appid = load_or_create_guid()

    iss = f"""\
; Auto-generated by make_installer_iss_dual.py
; Do not edit manually unless you know what you're doing.

#define ProductName "{PRODUCT_NAME}"
#define ProductVersion "{ver}"
#define BuildCode "{build_code}"
#define Publisher "{PUBLISHER}"
#define ExeCLI "{EXE_CLI}"
#define ExeGUI "{EXE_GUI}"

[Setup]
SourceDir=..
AppId={{{{{appid}}}}}
AppName={{#ProductName}}
AppVersion={{#ProductVersion}}
AppPublisher={{#Publisher}}
DefaultDirName={{autopf}}\\{{#ProductName}}
DefaultGroupName={{#ProductName}}
DisableProgramGroupPage=yes
OutputDir={OUT_DIR}
OutputBaseFilename=PixivLoginSetup_v{{#ProductVersion}}_{{#BuildCode}}

VersionInfoVersion={{#ProductVersion}}
VersionInfoProductVersion={{#ProductVersion}}
VersionInfoProductTextVersion={{#ProductVersion}}
VersionInfoCompany={{#Publisher}}
VersionInfoDescription=Pixiv OAuth Setup

Compression=lzma2
SolidCompression=yes
WizardStyle=modern
ArchitecturesInstallIn64BitMode=x64compatible
SetupIconFile={ICON_FILE}
UninstallDisplayIcon={{app}}\\pixiv_login_gui.exe

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

; --- Types let user pick CLI/GUI easily ---
[Types]
Name: "full"; Description: "Install CLI + GUI"
Name: "cli"; Description: "Install CLI only"
Name: "gui"; Description: "Install GUI only"
Name: "custom"; Description: "Custom installation"; Flags: iscustom

[Components]
Name: "cli"; Description: "Pixiv OAuth CLi"; Types: full cli custom; Flags: fixed
Name: "gui"; Description: "Pixiv OAuth GUi"; Types: full gui custom

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop icon for GUi"; GroupDescription: "Additional icons:"; Components: gui
Name: "addtopath"; Description: "Add CLi to PATH (recommended)"; GroupDescription: "CLI options:"; Components: cli

[Files]
Source: "{{#ExeCLI}}"; DestDir: "{{app}}"; Flags: ignoreversion; Components: cli
Source: "{{#ExeGUI}}"; DestDir: "{{app}}"; Flags: ignoreversion; Components: gui

[Icons]
Name: "{{group}}\\Pixiv OAuth GUi"; Filename: "{{app}}\\pixiv_login_gui.exe"; Components: gui
Name: "{{group}}\\Pixiv OAuth CLi"; Filename: "{{app}}\\pixiv_login_plus.exe"; Components: cli
Name: "{{commondesktop}}\\Pixiv OAuth GUi"; Filename: "{{app}}\\pixiv_login_gui.exe"; Tasks: desktopicon; Components: gui

[Run]
Filename: "{{app}}\\pixiv_login_gui.exe"; Description: "Launch Pixiv OAuth GUi"; Flags: nowait postinstall skipifsilent; Components: gui
Filename: "{{app}}\\pixiv_login_plus.exe"; Description: "Launch Pixiv OAuth CLi"; Flags: nowait postinstall skipifsilent; Components: cli

[UninstallDelete]
Type: filesandordirs; Name: "{{app}}"

[Code]
function NeedsAddPath(Param: string): Boolean;
begin
  Result := (Param = 'addtopath');
end;

function HasPathEntry(PathValue, Entry: string): Boolean;
var
  WrappedPath: string;
begin
  WrappedPath := ';' + PathValue + ';';
  Result := Pos(';' + Entry + ';', WrappedPath) > 0;
end;

function RemovePathEntry(PathValue, Entry: string): string;
var
  SearchFor, ReplaceWith: string;
begin
  SearchFor := ';' + Entry + ';';
  ReplaceWith := ';';

  Result := ';' + PathValue + ';';
  while Pos(SearchFor, Result) > 0 do
    StringChangeEx(Result, SearchFor, ReplaceWith, True);

  if (Length(Result) > 0) and (Copy(Result, 1, 1) = ';') then
    Delete(Result, 1, 1);
  if (Length(Result) > 0) and (Copy(Result, Length(Result), 1) = ';') then
    Delete(Result, Length(Result), 1);
end;

procedure RemovePathFromRegistry(RootKey: Integer);
var
  PathEnv, NewPath, AppPath: string;
begin
  if not RegQueryStringValue(RootKey, 'Environment', 'Path', PathEnv) then
    Exit;

  AppPath := ExpandConstant('{{app}}');
  NewPath := RemovePathEntry(PathEnv, AppPath);

  if NewPath <> PathEnv then
    RegWriteStringValue(RootKey, 'Environment', 'Path', NewPath);
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  PathEnv, NewPath, AppPath: string;
begin
  if (CurStep = ssPostInstall) and WizardIsTaskSelected('addtopath') then begin
    if not RegQueryStringValue(HKCU, 'Environment', 'Path', PathEnv) then
      PathEnv := '';

    AppPath := ExpandConstant('{{app}}');
    if not HasPathEntry(PathEnv, AppPath) then begin
      if (PathEnv <> '') and (Copy(PathEnv, Length(PathEnv), 1) <> ';') then
        PathEnv := PathEnv + ';';
      NewPath := PathEnv + AppPath;
      RegWriteStringValue(HKCU, 'Environment', 'Path', NewPath);
      // PATH changes apply to new processes after install
    end;
  end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usUninstall then begin
    RemovePathFromRegistry(HKCU);
    RemovePathFromRegistry(HKLM);
  end;
end;
"""

    out_path = Path(__file__).parent / "pixiv_login_installer_dual.iss"
    out_path.write_text(iss, encoding="utf-8")
    print("Wrote", out_path.name, "(version:", ver, "build:", build_code, "AppId:", appid + ")")

if __name__ == "__main__":
    main()
